# Generated by Django 4.0.3 on 2022-03-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
